// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ZKVote Bridge Contract
 * @notice Verifies Groth16 proofs for cross-chain voting from Ethereum
 *         using Stellar SBT membership proofs.
 *
 * Flow:
 * 1. Relayer watches Soroban, builds SBT state tree, posts sbtRoot here
 * 2. User generates Groth16 proof (bridge.circom) proving SBT membership
 * 3. User calls castVote() with proof + public signals (incl. memberAddr)
 * 4. Contract verifies proof via BN254 precompiles (EIP-196/197)
 * 5. Emits VoteForwarded event for Soroban relay
 * 6. Nullifier stored to prevent double-voting
 *
 * Gas target: < 500k gas for proof verification
 */
contract Bridge {
    // ============================================
    // EVENTS
    // ============================================

    event VoteForwarded(
        uint256 indexed daoId,
        uint256 indexed proposalId,
        uint256 nullifier,
        uint256 voteChoice,
        uint256 voteRoot,
        uint256 memberAddr,
        uint256 chainId
    );

    event SbtRootUpdated(
        uint256 indexed daoId,
        uint256 sbtRoot,
        uint256 blockNumber
    );

    event VoteRootUpdated(
        uint256 indexed daoId,
        uint256 indexed proposalId,
        uint256 voteRoot,
        uint256 blockNumber
    );

    event VerifierProposed(address indexed newVerifier, uint256 eta);
    event VerifierUpdated(address indexed newVerifier);
    event AdminTransferStarted(address indexed pendingAdmin);
    event AdminUpdated(address indexed newAdmin);
    event RootUpdaterUpdated(address indexed newRootUpdater);

    // ============================================
    // STATE
    // ============================================

    /// @notice Groth16 verifier contract (generated by snarkjs)
    address public verifier;

    /// @notice SBT contract address on Soroban (binds proofs to specific SBT)
    uint256 public sbtContractAddr;

    /// @notice SBT state roots per DAO (posted by rootUpdater)
    mapping(uint256 => uint256) public sbtRoots; // daoId => sbtRoot

    /// @notice Authoritative voting Merkle roots per DAO+proposal (#649)
    mapping(uint256 => mapping(uint256 => uint256)) public voteRoots; // daoId => proposalId => voteRoot

    /// @notice Nullifiers used per DAO+proposal (prevents double-voting)
    mapping(uint256 => mapping(uint256 => mapping(uint256 => bool)))
        public nullifiers; // daoId => proposalId => nullifier => used

    /// @notice Admin who can propose verifier changes and transfer admin
    address public admin;

    /// @notice Two-step admin transfer pending acceptor (#650)
    address public pendingAdmin;

    /// @notice Narrow role that may publish SBT / voting roots (#650)
    address public rootUpdater;

    /// @notice Chain ID for domain separation — bound into publicSignals (#649)
    uint256 public chainId;

    /// @notice Timelock delay for verifier rotation (#650)
    uint256 public constant VERIFIER_TIMELOCK = 2 days;

    address public pendingVerifier;
    uint256 public pendingVerifierEta;

    // ============================================
    // ERRORS
    // ============================================

    error OnlyAdmin();
    error OnlyRootUpdater();
    error OnlyPendingAdmin();
    error InvalidProof();
    error NullifierUsed();
    error InvalidVoteChoice();
    error ZeroNullifier();
    error SbtRootNotSet();
    error VoteRootNotSet();
    error VoteRootMismatch();
    error InvalidVerifier();
    error InvalidAddress();
    error ZeroMemberAddr();
    error TimelockNotElapsed();
    error NoPendingVerifier();
    error ChainIdMismatch();

    // ============================================
    // CONSTRUCTOR
    // ============================================

    /**
     * @param _verifier Address of the deployed Groth16 verifier contract
     * @param _sbtContractAddr Soroban SBT contract address (U256)
     */
    constructor(address _verifier, uint256 _sbtContractAddr) {
        if (_verifier == address(0)) revert InvalidAddress();
        verifier = _verifier;
        sbtContractAddr = _sbtContractAddr;
        admin = msg.sender;
        rootUpdater = msg.sender;
        chainId = block.chainid;
    }

    // ============================================
    // ADMIN / GOVERNANCE
    // ============================================

    /**
     * @notice Propose a new Groth16 verifier (timelocked, #650)
     */
    function proposeVerifier(address _newVerifier) external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (_newVerifier == address(0)) revert InvalidAddress();
        pendingVerifier = _newVerifier;
        pendingVerifierEta = block.timestamp + VERIFIER_TIMELOCK;
        emit VerifierProposed(_newVerifier, pendingVerifierEta);
    }

    /**
     * @notice Execute a previously proposed verifier after the timelock
     */
    function executeVerifier() external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (pendingVerifier == address(0)) revert NoPendingVerifier();
        if (block.timestamp < pendingVerifierEta) revert TimelockNotElapsed();
        address newVerifier = pendingVerifier;
        pendingVerifier = address(0);
        pendingVerifierEta = 0;
        verifier = newVerifier;
        emit VerifierUpdated(newVerifier);
    }

    /**
     * @notice Legacy immediate setVerifier — REMOVED. Use propose/execute.
     * @dev Kept name as revert to catch stale callers.
     */
    function setVerifier(address) external pure {
        revert TimelockNotElapsed();
    }

    /**
     * @notice Post a new SBT state root for a DAO
     */
    function updateSbtRoot(uint256 daoId, uint256 sbtRoot) external {
        if (msg.sender != rootUpdater && msg.sender != admin) revert OnlyRootUpdater();
        if (sbtRoot == 0) revert SbtRootNotSet();
        sbtRoots[daoId] = sbtRoot;
        emit SbtRootUpdated(daoId, sbtRoot, block.number);
    }

    /**
     * @notice Anchor the eligible-voter Merkle root for a DAO+proposal (#649)
     */
    function updateVoteRoot(
        uint256 daoId,
        uint256 proposalId,
        uint256 voteRoot
    ) external {
        if (msg.sender != rootUpdater && msg.sender != admin) revert OnlyRootUpdater();
        if (voteRoot == 0) revert VoteRootNotSet();
        voteRoots[daoId][proposalId] = voteRoot;
        emit VoteRootUpdated(daoId, proposalId, voteRoot, block.number);
    }

    function setRootUpdater(address newRootUpdater) external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (newRootUpdater == address(0)) revert InvalidAddress();
        rootUpdater = newRootUpdater;
        emit RootUpdaterUpdated(newRootUpdater);
    }

    /**
     * @notice Start two-step admin transfer (#650)
     */
    function transferAdmin(address newAdmin) external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (newAdmin == address(0)) revert InvalidAddress();
        pendingAdmin = newAdmin;
        emit AdminTransferStarted(newAdmin);
    }

    /**
     * @notice Accept admin role (must be pendingAdmin)
     */
    function acceptAdmin() external {
        if (msg.sender != pendingAdmin) revert OnlyPendingAdmin();
        admin = pendingAdmin;
        pendingAdmin = address(0);
        emit AdminUpdated(admin);
    }

    /**
     * @notice Legacy immediate setAdmin — REMOVED. Use transferAdmin/acceptAdmin.
     */
    function setAdmin(address) external pure {
        revert OnlyPendingAdmin();
    }

    // ============================================
    // CORE: VOTE CASTING
    // ============================================

    /**
     * @notice Cast a cross-chain vote with Groth16 proof
     * @param memberAddr Field-encoded Stellar member address (MUST match circuit)
     */
    function castVote(
        uint256 daoId,
        uint256 proposalId,
        uint256 voteChoice,
        uint256 nullifier,
        uint256 voteRoot,
        uint256 sbtRoot,
        uint256 memberAddr,
        bytes calldata proof
    ) external {
        if (nullifier == 0) revert ZeroNullifier();
        if (memberAddr == 0) revert ZeroMemberAddr();
        if (nullifiers[daoId][proposalId][nullifier]) revert NullifierUsed();
        if (voteChoice > 1) revert InvalidVoteChoice();

        if (sbtRoots[daoId] == 0) revert SbtRootNotSet();
        if (sbtRoot != sbtRoots[daoId]) revert SbtRootNotSet();

        // Vote root must be anchored on-chain — reject prover-chosen trees (#649)
        uint256 anchoredVoteRoot = voteRoots[daoId][proposalId];
        if (anchoredVoteRoot == 0) revert VoteRootNotSet();
        if (voteRoot != anchoredVoteRoot) revert VoteRootMismatch();

        // Public signals must match bridge.circom order including chainId (#649)
        uint256[9] memory publicSignals;
        publicSignals[0] = sbtContractAddr;
        publicSignals[1] = memberAddr;
        publicSignals[2] = daoId;
        publicSignals[3] = proposalId;
        publicSignals[4] = nullifier;
        publicSignals[5] = voteChoice;
        publicSignals[6] = voteRoot;
        publicSignals[7] = sbtRoot;
        publicSignals[8] = chainId;

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) =
            decodeProof(proof);

        bool valid = _verifyProof(a, b, c, publicSignals);
        if (!valid) revert InvalidProof();

        nullifiers[daoId][proposalId][nullifier] = true;

        emit VoteForwarded(
            daoId,
            proposalId,
            nullifier,
            voteChoice,
            voteRoot,
            memberAddr,
            chainId
        );
    }

    // ============================================
    // VIEW FUNCTIONS
    // ============================================

    function isNullifierUsed(
        uint256 daoId,
        uint256 proposalId,
        uint256 nullifier
    ) external view returns (bool) {
        return nullifiers[daoId][proposalId][nullifier];
    }

    function getSbtRoot(uint256 daoId) external view returns (uint256) {
        return sbtRoots[daoId];
    }

    function getVoteRoot(
        uint256 daoId,
        uint256 proposalId
    ) external view returns (uint256) {
        return voteRoots[daoId][proposalId];
    }

    // ============================================
    // INTERNAL: PROOF VERIFICATION
    // ============================================

    function _verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[9] memory publicSignals
    ) internal view returns (bool) {
        (bool success, bytes memory result) = verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[9])",
                a,
                b,
                c,
                publicSignals
            )
        );

        if (!success || result.length < 32) return false;
        return abi.decode(result, (bool));
    }

    function decodeProof(
        bytes calldata proof
    )
        internal
        pure
        returns (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c
        )
    {
        require(proof.length == 256, "Invalid proof length");

        a[0] = uint256(bytes32(proof[0:32]));
        a[1] = uint256(bytes32(proof[32:64]));

        b[0][0] = uint256(bytes32(proof[64:96]));
        b[0][1] = uint256(bytes32(proof[96:128]));
        b[1][0] = uint256(bytes32(proof[128:160]));
        b[1][1] = uint256(bytes32(proof[160:192]));

        c[0] = uint256(bytes32(proof[192:224]));
        c[1] = uint256(bytes32(proof[224:256]));
    }
}
