const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * Deploy Bridge + verifier.
 *
 * Production: requires Verifier.sol generated by circuits/compile_bridge.sh
 * and copied into contracts/ (see that script). Set ALLOW_MOCK_VERIFIER=1
 * only for local/CI tests (#650).
 */
async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  const allowMock = process.env.ALLOW_MOCK_VERIFIER === "1";
  const verifierArtifact = path.join(__dirname, "../contracts/Verifier.sol");
  const hasRealVerifier = fs.existsSync(verifierArtifact);

  let verifierAddr;

  if (hasRealVerifier && !allowMock) {
    const Verifier = await hre.ethers.getContractFactory("Verifier");
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();
    verifierAddr = await verifier.getAddress();
    console.log("Verifier (production) deployed to:", verifierAddr);
  } else if (allowMock) {
    console.warn(
      "WARNING: Deploying MockVerifier (ALLOW_MOCK_VERIFIER=1). Not for production.",
    );
    const MockVerifier = await hre.ethers.getContractFactory("MockVerifier");
    const verifier = await MockVerifier.deploy();
    await verifier.waitForDeployment();
    verifierAddr = await verifier.getAddress();
    console.log("MockVerifier deployed to:", verifierAddr);
  } else {
    throw new Error(
      "No Verifier.sol found and ALLOW_MOCK_VERIFIER is not set.\n" +
        "Run circuits/compile_bridge.sh and copy build/Verifier.sol into " +
        "contracts/bridge/evm/contracts/, or set ALLOW_MOCK_VERIFIER=1 for tests.",
    );
  }

  const sbtContractAddr = process.env.SBT_CONTRACT_ADDR || "1";
  console.log("SBT contract address:", sbtContractAddr);

  const Bridge = await hre.ethers.getContractFactory("Bridge");
  const bridge = await Bridge.deploy(verifierAddr, sbtContractAddr);
  await bridge.waitForDeployment();
  const bridgeAddr = await bridge.getAddress();
  console.log("Bridge deployed to:", bridgeAddr);

  console.log("\nDeployment complete!");
  console.log("Verifier:", verifierAddr);
  console.log("Bridge:", bridgeAddr);
  console.log("chainId:", (await bridge.chainId()).toString());
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
